# Generated by Django 5.1.1 on 2024-09-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
                ('level', models.CharField(choices=[('Beginer', 'Débutant'), ('Intermediaire', 'Intermediaire'), ('Avance', 'Avancé')], default='Beginer', max_length=15, verbose_name='Niveau ')),
                ('target_area', models.CharField(choices=[('Bras', 'Bras'), ('Poitrine', 'Poitrine'), ('Jambe', 'Jambe'), ('Abdos', 'Abdos'), ('Epaule', 'Epaule')], default='Bras', max_length=10, verbose_name='Zone ciblée ')),
                ('duration', models.PositiveIntegerField(blank=True, verbose_name='Durée ')),
                ('repetition', models.PositiveIntegerField(blank=True, verbose_name='Répétition ')),
                ('description', models.TextField(verbose_name='Description ')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
            },
        ),
    ]
