# Generated by Django 5.1.1 on 2024-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercisemodel_repetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisemodel',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée '),
        ),
    ]
