# Generated by Django 5.1.1 on 2024-09-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('target_area', models.CharField(choices=[('Bras', 'Bras'), ('Poitrine', 'Poitrine'), ('Jambe', 'Jambe'), ('Abdos', 'Abdos'), ('Epaule', 'Epaule')], default='Bras', max_length=10, verbose_name='Zone ciblée ')),
                ('starting', models.DateField(verbose_name='Date de début ')),
                ('ending', models.DateField(verbose_name='Date de fin ')),
                ('slug', models.SlugField(unique=True)),
                ('exercices', models.ManyToManyField(to='exercise.exercisemodel', verbose_name='Exercices ')),
            ],
            options={
                'verbose_name': 'Programme',
                'verbose_name_plural': 'Programmes',
            },
        ),
    ]
