# Generated by Django 5.1.1 on 2024-09-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_programmodel_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programmodel',
            name='routine',
        ),
        migrations.AddField(
            model_name='programmodel',
            name='routine',
            field=models.ManyToManyField(to='program.routinemodel', verbose_name='Nom de la routine '),
        ),
    ]
